### ISSUE TITLE
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes

### ISSUE THREAD

**Issue by franktopel** [WebReflection/html-parsed-element#7]
We are trying to integrate `html-parsed-element` into our project's component library.

Currently, if we load the bundled components in the `head` of the HTML, this is what we're getting:

`Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes`

I assume this is causing alot of follow-up errors:

![image](https://user-images.githubusercontent.com/10668603/48273196-aa3d8b00-e440-11e8-8213-cb48199b2220.png)

In the constructor we're only setting custom (non-inherited) component properties which are not DOM-related.

We do, though, have defined top level getters and setters on the component itself, which do try to access children. Also, we have `attributeChangedCallback` calling these setters.

**Any idea what could be going on here?**

P.S.: I assume there's alot more to fix on our side, but the thing that makes me publish this as an issue here is the fact that **`parsedCallback` in the above scenario definitely gets called with zero children present.** If I wrap the parsedCallback code in a `setTimeout(() => { ... }, 1}` the children **are** available.

**Comment by franktopel** [comment]
When I select the element in the Chrome inspector, and ask for its constructor via `$0.constructor` I do actually get the constructor I'm expecting, e.g. `BmTableWrapper`, not `HTMLParsedElement`. So the custom element registration seemingly hasn't failed completely.

It does strike me though, that the error messages do not show this: `at HTMLElement.parsedCallback (bm-popup-link.js:58)` - shouldn't this read `at BmPopupLink.parsedCallback (bm-popup-link.js:58)`?

**Comment by WebReflection** [comment]
I have no idea how to help because I have zero code to test/verify/debug.

A screenshot of errors is not a good way to ask for help.

**Comment by WebReflection** [comment]
to clarify:

  * I have no idea if you are transpiling
  * I have no idea if you are using polyfills
  * I have no idea what any of your code does
  * I have no layout to test
  * I have no idea if you are creating children procedurally or via DOM
  * I have no idea if you define custom elements before or after these are already live

.. and so on and so fort.

If you'd like my help, please help me help you first. Thanks.

**Comment by franktopel** [comment]
That's why I'm asking for your thoughts as of what could possibly cause parsedCallback to ever get called without children present (no, not the no-whitespace-noone-has-siblings-edge-case). Problem is, this is company code which I cannot publish anywhere.

- transpilation using Babel 7 and @babel/preset-env
- using your polyfill 1.11.0 (but observing the problems in current Chrome, so assuming it doesn't interfere here)
- we do not create any HTML procedurally except inside our component's setups
- quoting myself from the initial post:
  - *currently, if we load the bundled components in the `head` of the HTML, this is what we're getting*

**Comment by WebReflection** [comment]
This is how I usually fix bugs:

  * there is a minimal case that reproduces it
  * I understand the issue and fix it

Until the first point is represented by a huge image that never even names this module, or any of its methods, anywhere, I'm afraid I cannot do much.

I'll close this until there is a way for me to take an action.

**Comment by franktopel** [comment]
I'm okay with you closing this, yet I'm still asking your thoughts as of what could possibly cause `parsedCallback` to ever get called without children present in the (quite static) scenario I described. Speculation welcome.

**Comment by WebReflection** [comment]
I'm afraid I have enough cases where my code never had anything to do with issues they filed me, which is why I am telling you, if your closed source company would like to use my open source code and spend my free unpaid time, you should try a little harder with bugs reports.

Thanks for your understanding.

**Comment by franktopel** [comment]
Ofc I do understand this. Maybe I thought you'd handle this a little differently considering the amount of time I spent on the creating the foundation/ignition point of this package as well. As I don't have any other way to communicate with you, I chose to open an issue for this, as the fact that there are circumstances in which `parsedCallback` gets called too early might raise your interest.

**Comment by WebReflection** [comment]
@franktopel I am a full time employee ... and these bugs are honestly the most turnoff ever for any open source contributor.

I'm sorry if me incapable of literally doing anything for the reasons explained somehow disappointed your expectations.

**Comment by WebReflection** [comment]
_TL;DR_ **anything** could be the reason of this issue. I don't have time for this.

**Comment by franktopel** [comment]
Just to let you know, the reason `parsedCallback` was called too early boiled down to the check if any of the parent nodes does have a `nextSibling`. I cannot explain why, but obviously there's cases where an element does not have a next sibling, but it does have an ancestor element that does. At this point in time again, children are not available. As a result, that means that the current `HTMLParsedElement` implementation does **not make it safe to setup a custom element**. The problem occurs in the parse case (with custom elements being defined up front).

**Comment by franktopel** [comment]
Changing

```javascript
const isParsed = el => {
    do {
        if (el.nextSibling) return true;
    } while ((el = el.parentNode));
    return false;     
};
```
to

```javascript
const isParsed = el => !!el.nextSibling;
``` 

fixed it for our setup, which is kind of unsatisfying since that obviously will ~fail~ delay calling `parsedCallback` until `DOMContentLoaded` in the

```html
<div><my-el><p>child here</p></my-el></div>
```

case.

**Comment by WebReflection** [comment]
@franktopel I'm glad you found the issue and took the time to come back, but the hack comes from AMP HTML, and AFAIK they never had an issue with it.

However, I still believe some component setup is messing up the Dom, causing the issue you are seeing.

Could you please verify if writing this `setTimeout(parsedCallback, 0, el);` instead of just `parsedCallback(el);` inside the `cleanUp` callback has the same issue?

If not, then delaying the setup when `!el.nextSibling` seems to be a better compromise than waiting at all costs for DOMContentLoaded, but if you have the same issue, then we need to understand what the heck is going on 'cause a try / catch around `el[method]();` won't solve anything, eventually make it worse.

**Comment by WebReflection** [comment]
P.S. could you also please tell me if you are using Shadow DOM and slots ? I think nodes moved into slots might also interfere with the `nextSibling` logic and throws unexpected errors

**Comment by WebReflection** [comment]
P.S.2 can you also perhaps try this ?

```js
const isParsed = el => {
    do {
        if (el.nextSibling) return true;
    } while ((el = el.parentNode) && 'nextSibling' in el);
    return false;     
};
```

**Comment by franktopel** [comment]
We're not using shadow DOM. This is what our datatable component looks like (very stripped down):

```html
<data-table>
  <table slot="table"><!-- common table html stuff --></table>
</data-table>
```

```javascript
export default class DataTable extends HTMLParsedElement {
  parsedCallback() {
    const table = this.querySelector('[slot=table]'); //  this is null
  }
}
```

**Comment by WebReflection** [comment]
then I have another script to test, since slots are a weird beast:

```js
const isParsed = el => {
    do {
        if (el.nextSibling) return true;
    } while ((el = el.parentNode) && !el.slot);
    return false;     
};
```

**Comment by franktopel** [comment]
```javascript
const isParsed = el => {
    do {
        if (el.nextSibling) return true;
    } while ((el = el.parentNode) && !el.slot);
    return false;
};
``` 
results in 

`this.slottedTable` being `null` at the beginning of `parsedCallback`. 

This is the getter:

```javascript
get slottedTable() {
    if (!this._slottedTable) {
        this._slottedTable = this.querySelector('[slot="table"]') || this.querySelector('table');
    }
    return this._slottedTable;
}
```

## Edit:

I don't think changing the `while`condition that way will have any effect since neither the `data-table` element nor any of its ancestors have a `slot` attribute - again this is the HTML structure for our component:

```html
<data-table>
  <table slot="table">/* common table html stuff */</table>
</data-table>
```

The slot attribute is on the **child** table.

**Comment by WebReflection** [comment]
can you please give the async version a try?
https://github.com/WebReflection/html-parsed-element/issues/7#issuecomment-444452170

**Comment by franktopel** [comment]
The async version was the very first attempt to fix it, and it worked. 

See also my initial post: *If I wrap the `parsedCallback` code in a `setTimeout(() => { ... }, 1}` the children **are available**.*

I didn't want to go with that as it feels very undesirable to have hundreds of timeouts occuring while a single page is being rendered.

**Comment by WebReflection** [comment]
well, just to clarify, it will be used only if `isParsed(el) && !el.nextSibling`, which is a limited amount of use cases, but I can also write code that doesn't create hundreds timeouts, as I've done tons of times in the past.

**Comment by WebReflection** [comment]
can you please check if this version would work?
https://github.com/WebReflection/html-parsed-element/pull/8

**Comment by franktopel** [comment]
Will immediately check as soon as I'm in the office again, which will be tomorrow ~ 10:30 a.m. Thanks for caring. In the meantime, if possible, can you explain your approach?

**Comment by franktopel** [comment]
If I get it right, you're using `requestAnimationFrame` to delay execution of `parsedCallback`. That doesn't seem like a desirable approach either - in some tests we did on the road to HTMLParsedElement (6 weeks back) we tried using `requestAnimationFrame` too, ending up with components' `parsedCallback` being called _even after_ `DOMContentLoaded`. Will give it a ride nonetheless now, but it will take some time as we will have to thoroughly analyze that in the performance tab.

**Comment by WebReflection** [comment]
to be noted:

 1. I am not using one rAF per each callback, I'm stacking all of them. This means better scheduling/visual performance in general
 2. I ended up this way because otherwise you could have situations where some node is upgraded but others might not be upgraded, resulting in a pretty messy flow if a container with a `nextSibling` but a single node inside that has no sibling and might through if accessed by its parent.

The max 16ms delay should be irrelevant in the real world but it should fix in a reliable way this issue.

Please let me know your findings, thanks.

**Comment by franktopel** [comment]
Looking good so far. Added a `console.log(document.readyState)` at the beginning of `parsedCallback` and so far all initialization seems to happen before `DOMContentLoaded`. We will do the deep dive into the performance measuring tool in Chrome tomorrow. For the time being, thank you for your work!

**Comment by franktopel** [comment]
We have done tests in our real-world application now.

The good news is that all the components work in all scenarios (parse-case, upgrade-case, dynamic creation-case).

The *really* bad news is that most components now only do their `parsedCallback` while the `document.readyState` is already `interactive`, which means that listeners registered on `DOMContentLoaded` event can no longer reliably access HTML created by our webcomponents.

Will do further analysis tomorrow and keep you updated.

**Comment by WebReflection** [comment]
If I understand correctly, that means all I am missing is a way to force the queue as soon as DOMContentLoaded happens, considering it will be the first one to fire since any other logic assumes already these components are available, right?

**Comment by WebReflection** [comment]
I've just updated the branch with a `document.addEventListener(DCL, upgrade);` right before the class declaration. Please have a look and let me know if everything is now fine, thanks.

**Comment by WebReflection** [comment]
P.S. I've also changed `upgrade` to avoid race conditions

```js
  const upgrade = () => {
    queue.splice(0).forEach(info => {
      if (init.get(info[0]) !== true) {
        init.set(info[0], true);
        info[0][info[1]]();
      }
    });
  };
```

**Comment by franktopel** [comment]
According to all testing we've done so far (including the real world application using our web components) this seems to be the correct solution. In one of our components I added the dynamic creation of an element with an id and appending that to the `document.body`.

Further down the page I've put a simple `script` block registering a `DOMContentLoaded` listener which is trying to access that dynamically created element and it works!

I keep being amazed that the spec forces us to do all this.

**Comment by WebReflection** [comment]
@franktopel can you confirm the latest patches in the merge request were involved in your tests?

In few words, can I merge that request?

**Comment by franktopel** [comment]
Yes, my statement referred to your latest changes with adding a DCL listener and your latest changes to the `upgrade` function. Thanks alot for your effort! We will do more testing, but so far haven't found any issues remaining.

**Comment by WebReflection** [comment]
so, `0.4.0` is up and running 👋

**Comment by jonathantneal** [comment]
I ran into this same error and it was because I was assigning `this.slot` within the constructor.

```js
// in my case, it was:
this.slot = this.shadowRoot.appendChild(document.createElement('slot'));
```

Here is another minimal example:

```html
<script>
class ExampleIssueElement extends HTMLElement {
	constructor() {
		super();

		this.slot = document.createElement('slot');
	}
}

customElements.define('example-issue', ExampleIssueElement);
</script>
<example-issue></example-issue>
<!-- will throw: “Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes” -->
```

That code ends up assigning an attribute to the Custom Element because `Element.prototype.slot` assigns an attribute (https://developer.mozilla.org/en-US/docs/Web/API/Element/slot).

Custom Elements and slots are often used together, so I am sharing this to potentially help others.

**Comment by WebReflection** [comment]
Hi @jonathantneal, few questions:

  * were you using the latest version ?
  * were you doing that within the `parsedCallback` method or once `this.parsed` was true ?

If not, please show a failing example otherwise your comment won't really help anyone (if that was your intent).

Thanks.

**Comment by jonathantneal** [comment]
The problem has nothing to do with your parsed element. I’ve added another minimal example and clarified when the bug occurred. You happen to be the first search result for this particular problem, but if it’s not helpful to anyone then we can remove it. Your repo; your rules. 😄

**Comment by WebReflection** [comment]
@jonathantneal 

> The problem has nothing to do with your parsed element.

but my parsed element fixes it, that's what I'm asking.

**Comment by Offirmo** [comment]
For fellow googlers: https://stackoverflow.com/a/43837330
